targets:
  $default:
    builders:
      moor_generator:
        enabled: false
      moor_generator|moor_generator_not_shared:
        enabled: false
      entity_sync_generator:
        enabled: true
