name: entity_sync
version: '0.0.1'
description: An entity sync library for Dart developers.
homepage: https://github.com/cmberryau/entity_sync

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  http: 0.12.2
  moor: ^3.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  mockito: 4.1.1
  build_runner: ^1.10.0
  moor_generator: ^3.1.0
  moor_ffi: ^0.5.0
