name: entity_sync
description: An entity sync library for Dart developers.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  moor: ^3.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  mockito: 4.1.1
  build_runner: ^1.10.0
  moor_generator: ^3.1.0
